version: '3'
services:
  postgres:
    image: 'postgres:10'
  # redis:
  #   image: 'redis:latest'
  # server:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./server
  #   volumes:
  #     - /app/node_modules #keep node_modules folder intact
  #     - ./server:/app #copy all sever files to /app folder
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - PGUSER=postgres
  #     - PGHOST=postgres
  #     - PGDATABASE=postgres
  #     - PGPASSWORD=postgres_password
  #     - PGPORT=5432
      